version: '1.0'
steps:
  main_clone:
    type: git-clone
    description: Cloning main repository...
    repo: pinpt/agent
    revision: '${{CF_BRANCH}}'
    stage: clone
  build:
    title: Building docker image
    type: build
    image_name: pinpt/agent
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: docker/cloudbuild/Dockerfile
    stage: build
  parallel_push:
    type: parallel
    stage: push
    steps:
      annotate_build:
        title: Annotating Build
        image: '${{build}}'
        working_directory: IMAGE_WORK_DIR
        commands:
          - echo Annotating Build...
        on_success:
          metadata:
            set:
              - '${{build.imageId}}':
                  - CF_QUALITY: true
        on_error:
          metadata:
            set:
              - '${{build.imageId}}':
                  - CF_QUALITY: false
      push:
        title: Pushing image to gitlab
        type: push
        image_name: pinpt/agent
        registry: gitlab-pinpt
        candidate: '${{build}}'
        tags:
          - '${{CF_BRANCH_TAG_NORMALIZED}}'
          - '${{CF_REVISION}}'
      dockerhub_all:
        title: Pushing image tagged with commit to Dockerhub
        type: push
        image_name: pinpt/agent
        registry: dockerhub
        candidate: '${{build}}'
        tags:
          - '${{CF_BRANCH_TAG_NORMALIZED}}'
          - '${{CF_REVISION}}'
      dockerhub_edge:
        title: Pushing edge image to Dockerhub
        type: push
        image_name: pinpt/agent
        registry: dockerhub
        candidate: '${{build}}'
        tags:
          - edge
          - master
        when:
          branch:
            only:
              - master
      dockerhub_beta:
        title: Pushing beta image to Dockerhub
        type: push
        image_name: pinpt/agent
        registry: dockerhub
        candidate: '${{build}}'
        tags:
          - beta
        when:
          branch:
            only:
              - beta
  approval_for_push:
    type: pending-approval
    title: Tag this Docker image as stable in Dockerhub?
    description: Do you want to tag the build as stable/latest in Dockerhub?
    stage: deploy
    timeout:
      duration: 1
      finalState: denied
    when:
      branch:
        only:
          - master
  dockerhub_stable:
    title: Pushing stable image to Dockerhub
    type: push
    stage: deploy
    image_name: pinpt/agent
    registry: dockerhub
    candidate: '${{build}}'
    tags:
      - stable
      - latest
    when:
      branch:
        only:
          - master
          - stable
stages:
  - clone
  - build
  - integration
  - push
  - deploy
